#!/usr/bin/env bash

FOLDER="/mnt/nas/media/movies/"

openvid () {
  NAME="$(find "$FOLDER" -type f | sed "s|$FOLDER||" | dmenu -l 15)" || exit 0
  [ -n "$NAME" ] && mpv "$FOLDER$NAME" >/dev/null 2>&1
}

openvid