#!/usr/bin/env bash
# relative path to mpd's music directory *must* be used. absolute path will not be read by mpd.

file="$(mpc listall | dmenu -i -l 10)" || exit 0
if [ -n "$file" ]; then
  notify-send "Playing $file"
  mpc clear
  mpc add "$file"
  mpc play
fi