#!/usr/bin/env bash
# filepath: /etc/nixos/config/suckless/dmenu/scripts/dmenu_mpv

FOLDER="$HOME/Vidéos/"

openvid () {
  NAME="$(find "$FOLDER" -maxdepth 1 -type f -printf '%f\n' | dmenu -l 15)" || exit 0
  [ -n "$NAME" ] && mpv "$FOLDER$NAME" >/dev/null 2>&1
}

openvid