#!/bin/bash

if [ -n "$@" ];
then
    if [ $1 == "edit" ]
    then
        nvim .gitignore
    else
        cp /home/lucasskvn/delivery/my_scripts/.gitignore $1
    fi
else
    echo "J'ai besoin d'un fichier en paramètre ou écrivez edit pour editer le gitignore."
fi
