#!/bin/bash

if [ $1 == cstyle ];
then
    firefox https://intra.epitech.eu/file/public/technical-documentations/C/epitech_c_coding_style.pdf
    clear
elif [ $1 == intra ];
then
    firefox https://intra.epitech.eu/
    clear
elif [ $1 == mouli ];
then
    firefox my.epitech.eu
else
    # Récupérer le nom du répertoire courant
    DIR_NAME=$(basename "$PWD")

    # Construire l'URL
    URL="https://github.com/EpitechPGEPromo2029/${DIR_NAME}/tree/main"

    # Ouvrir l'URL dans Firefox
    firefox "$URL"
    clear
fi
